### ISSUE TITLE
Deprecate Table class

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx-Project/Utilities#111]
AFAIK the only place we were using the `Table` class was in PluginPlay (for generating module documentation). I forget why, but that wasn't cutting it and @zachcran ultimately hooked up `libfort` (Library to create FORmatted Tables, nothing to do with Fortran...) instead. IIRC @keceli said that the unit tests for the `Table` class were giving him problems, assuming `Table` isn't being used anymore, then deleting it is the easiest way to fix those problems.

Tasks:
- [x] verify that `Table` class is not used anywhere else
- [ ] delete it (no need for attic or anything)

**Comment by keceli** [comment]
I just checked and confirm that it is only included in PluginPlay and they are not being used. I can go ahead and update PluginPlay and Utilities, if you aren't doing it already.

https://github.com/NWChemEx-Project/PluginPlay/blob/master/src/pluginplay/printing/detail_/print_results.cpp
https://github.com/NWChemEx-Project/PluginPlay/blob/master/src/pluginplay/printing/detail_/print_inputs.cpp
https://github.com/NWChemEx-Project/PluginPlay/blob/master/src/pluginplay/printing/detail_/print_submodules.cpp

**Comment by ryanmrichard** [comment]
@keceli I'm not, so go for it.

**Comment by zachcran** [comment]
@ryanmrichard @keceli Is this issues ready to be closed, or is there more to do on it?

**Comment by ryanmrichard** [comment]
I think #112 fixed this. People should feel free to reopen if that's not the case.
