### ISSUE TITLE
Test failure with Clang 9.0.1

### ISSUE THREAD

**Issue by keceli** [NWChemEx-Project/Utilities#68]
With clang 9.0.1 configure and build was ok, but one ctest example failed. 
```
/container/nwx/Utilities/tests/printing/print_stl.cpp:339
...............................................................................

/container/nwx/Utilities/tests/printing/print_stl.cpp:346: FAILED:
  REQUIRE( ss.str() == corr )
with expansion:
  "[<St3mapIidSt4lessIiESaISt4pairIKidEEE 0x18b6be0>,
  <St3mapIidSt4lessIiESaISt4pairIKidEEE 0x18b6c10>]"
  ==
  "[{(0 : 1.1), (1 : 2.2), (2 : 3.3)}, {(0 : 4.4), (1 : 5.5), (2 : 6.6)}]"

===============================================================================
test cases: 159 | 158 passed | 1 failed
assertions: 797 | 796 passed | 1 failed
```
This doesn't seem to be related to any recent changes, this test was failing with the same error before and gcc 8.3.0 build still passes all tests. 
I see that cmake uses the same compiler flags for g++ and clang++. Maybe this can be a problem.
```CMAKE_CXX_FLAGS:STRING=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/envs/cppyy-example/include```

**Comment by keceli** [comment]
Looks like the origin of the problem with print_stl unit test is the check for `is_printable`. It returns True for gcc and False for clang for nested template types. I tried a couple of things, but didn't work.

How about using [fmt](https://github.com/fmtlib/fmt)? It has many other nice features and already part of C++20.

**Comment by zachcran** [comment]
I am running into this issue on GCC 12.2.1 right now, too. I am on Manjaro Linux 22.0.4 with all of my packages up-to-date. I can build each repo in the NWChemEx stack, and most tests pass, so there does not seem to be an issue with my GCC installation. Here are the generation, build, and test logs:

Generation log: [OUTPUT.GEN](https://github.com/NWChemEx-Project/Utilities/files/10885691/OUTPUT.GEN.txt)
Build log: [OUTPUT.BUILD](https://github.com/NWChemEx-Project/Utilities/files/10885690/OUTPUT.BUILD.txt)
Test log: [OUTPUT.TEST](https://github.com/NWChemEx-Project/Utilities/files/10885685/OUTPUT.TEST.txt)
Toolchain: [toolchain.cmake](https://github.com/NWChemEx-Project/Utilities/files/10885704/toolchain.cmake.txt)

**Comment by twindus** [comment]
@keceli Can you work on this?
